import type { NextPage } from "next";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import SignUp from "../components/auth/SignUp";
import HomePage from "../components/HomePage";
import { auth } from "../firebase/clientApp";

const Home: NextPage = () => {
	const [user, loading, error] = useAuthState(auth);

	return (
		<div className="max-w-[1200px] flex-1 h-full flex flex-col px-3">
			<Head>
				<title>Moods</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{loading && "Loading..."}
			{!loading && <>{user ? <HomePage /> : <SignUp />}</>}
		</div>
	);
};

export default Home;
